PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

CONSTRUCT {
  ?this a skos:Concept ;
    skos:prefLabel ?prefLabel ;
    skos:inScheme ?scheme .
}
WHERE {
  BIND(?_iri AS ?this)
  ?this a skos:Concept ;
    skos:prefLabel ?prefLabel ;
    skos:inScheme ?scheme .
  FILTER(?scheme = <http://vocab.getty.edu/aat/>)
}
